### ISSUE TITLE
I can't see notifications

### ISSUE THREAD

**Issue by jacklee-5** [stuartleeks/wsl-notify-send#5]
Hi,

Thanks for your great work!
This will be useful for me because I use WSL a lot.
I tried to use wsl-notify-send.exe on Windows, but I couldn't see any notifications.
Do you know any Windows settings can block notifications?

**Comment by stuartleeks** [comment]
Hi @jacklee-5, if you have "Focus assist" mode or something similar on then I find that the notifications don't pop up. They are still shown in the notifications area if you click on it.

Hope that helps!

**Comment by jacklee-5** [comment]
Oh, Thanks! I can see notifications after changing the 'focus assist' configuration. 👍

**Comment by stuartleeks** [comment]
Great - glad it's working :-)
(thanks for letting me know)
